# This dockerfile is user to build the output files.
# It contains all the required dependencies
FROM python:3.6-alpine

WORKDIR /site

COPY requirements.txt requirements.txt
RUN apk add \
      make \
      bash \
    && pip install -r requirements.txt

VOLUME /site
CMD ["sh", "-c", "make clean && make html"]