FROM python:3.6-alpine

WORKDIR /site

COPY requirements.txt requirements.txt
RUN apk add \
      make \
      bash \
    && pip install -r requirements.txt

CMD ["sh", "-c", "make clean && make html"]